/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import beans.AccountBean;
import dao.AccountDAO;
import dao.CustRecordDAO;
import daoImp.AccountDAOImpl;
import daoImp.CustRecordDAOImpl;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 

/**
 *
 * @author xyz
 */
public class CustomerDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountFrame
     */
    public CustomerDetailsFrame() throws SQLException {
        initComponents();
        setTable();
        setDate();
    }
    
    private void setDate(){
        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat sd1 = new SimpleDateFormat("yyyy-MM-dd");
        String date = sd.format(d);
        String date1 = sd1.format(d);
    }
    
    private void setDatePicker(){
       
    }

    public void setTable() throws SQLException {
        AccountDAO accountDAO = new AccountDAOImpl();
        tableAccountsFrame.setModel(buildTableModel(accountDAO.viewAllAccountResultSet()));
    }

    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    
    private void setAllText(){
        try {
            int id = (int) tableAccountsFrame.getValueAt(tableAccountsFrame.getSelectedRow(), 0);
            
            AccountBean accountBean = new AccountBean();
            accountBean.setAccountId(id);
            
            AccountDAO accountDAO = new AccountDAOImpl();
            ArrayList<AccountBean> list = (ArrayList<AccountBean>) accountDAO.setAllTxt(accountBean);
            for (AccountBean accountBean1 : list) {
                txtName.setText(accountBean1.getAccountName());
                txtContact.setText(accountBean1.getAccountConnect());
                txtAreaDescription.setText(accountBean1.getDescription());
            }
            
            CustRecordDAO crdao = new CustRecordDAOImpl();
            tableBills.setModel(buildTableModel(crdao.getAllBills(accountBean)));
        } catch (SQLException ex) {
            Logger.getLogger(CustomerDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void clearAll() {
        txtName.setText("");
        txtContact.setText("");
        txtAreaDescription.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccountsFrame = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        txtName1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBills = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableAccountsFrame2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateChooserPanel = new datechooser.beans.DateChooserPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 20, 310, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("نالو");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 20, 100, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("اڊريس");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 160, 100, 40));

        txtContact.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 90, 310, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnUpdate.setText("<>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 360, 90, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 360, 90, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnDelete.setText("-");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 360, 90, -1));

        tableAccountsFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableAccountsFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAccountsFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountsFrameMouseClicked(evt);
            }
        });
        tableAccountsFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableAccountsFrameKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccountsFrame);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 500, 720));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton4.setText("< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 840, 180, -1));

        txtAreaDescription.setColumns(20);
        txtAreaDescription.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtAreaDescription.setRows(5);
        jScrollPane2.setViewportView(txtAreaDescription);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 160, 310, 160));

        txtName1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 500, -1));

        tableBills.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBillsMouseClicked(evt);
            }
        });
        tableBills.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableBillsKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tableBills);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 830, 340));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("بل");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, -1, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("مليل");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 480, -1, 50));

        tableAccountsFrame2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableAccountsFrame2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAccountsFrame2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountsFrame2MouseClicked(evt);
            }
        });
        tableAccountsFrame2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableAccountsFrame2KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tableAccountsFrame2);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 830, 320));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("موبائل");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 90, 100, 40));

        txtName2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 820, 310, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("مليل");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 820, 100, 40));

        dateChooserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
            (java.awt.Color)null,
            (java.awt.Color)null,
            (java.awt.Color)null,
            (java.awt.Color)null));
    dateChooserPanel.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 21));
    jPanel2.add(dateChooserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 430, 450, 360));

    jButton1.setText("jButton1");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1910, 900));

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel6.setText("خاتو");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, 40));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableAccountsFrameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableAccountsFrameKeyReleased
        setAllText();
    }//GEN-LAST:event_tableAccountsFrameKeyReleased

    private void tableAccountsFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountsFrameMouseClicked
        setAllText();
    }//GEN-LAST:event_tableAccountsFrameMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add1Update2Delete3(1);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        add1Update2Delete3(2);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        add1Update2Delete3(3);       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBillsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableBillsMouseClicked

    private void tableBillsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableBillsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableBillsKeyReleased

    private void tableAccountsFrame2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountsFrame2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAccountsFrame2MouseClicked

    private void tableAccountsFrame2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableAccountsFrame2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAccountsFrame2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date d = dateChooserPanel.getSelectedDate().getTime();
        SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat sd1 = new SimpleDateFormat("yyyy-MM-dd");
        String date = sd.format(d);
        String date1 = sd1.format(d);
        System.out.println(date);
        System.out.println(date1);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void add1Update2Delete3(int one) {
        String name = txtName.getText();
        String contact = txtContact.getText();
        String description = txtAreaDescription.getText();

        AccountBean accountBean = new AccountBean();
        accountBean.setAccountName(name);
        accountBean.setAccountConnect(contact);
        accountBean.setDescription(description);
           
        AccountDAO accountDAO = new AccountDAOImpl();
        if (one == 1) {
            if (accountDAO.addAccountDetails(accountBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    JOptionPane.showMessageDialog(this, "Account added successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(CustomerDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add the account!");
            }
        } else if(one==2) {
            int id = (int) tableAccountsFrame.getValueAt(tableAccountsFrame.getSelectedRow(), 0);
            accountBean.setAccountId(id);
            if (accountDAO.updateAccountDetails(accountBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    JOptionPane.showMessageDialog(this, "Account updated successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(CustomerDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the account!");
            }
        }else if(one==3){
                int id = (int) tableAccountsFrame.getValueAt(tableAccountsFrame.getSelectedRow(), 0);
                accountBean.setAccountId(id);
                if (accountDAO.deleteAccountDetails(accountBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    JOptionPane.showMessageDialog(this, "Account deleted successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(CustomerDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the account!");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CustomerDetailsFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CustomerDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private datechooser.beans.DateChooserPanel dateChooserPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableAccountsFrame;
    private javax.swing.JTable tableAccountsFrame2;
    private javax.swing.JTable tableBills;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    // End of variables declaration//GEN-END:variables
}
