/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import beans.BillBean;
import beans.BillDetailsBean;
import beans.ProductBean;
import dao.BillDAO;
import dao.BillDetailsDAO;
import daoImp.BillDAOImpl;
import daoImp.BillDetailsDAOImpl;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author xyz
 */
public class QuantityDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuantityDialog
     */
    public QuantityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setValues();
    }

    private void setValues() {
        ProductBean pb = OrderFrame.probean;
        String proSinName = pb.getProductNameSindhi();
        String size = pb.getSize();
        int quan = pb.getQuantity();
        lblItem.setText(proSinName);
        lblSize.setText(size);
        lblQuantity.setText(String.valueOf(quan));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtQuatity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuatity.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtQuatity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuatityKeyReleased(evt);
            }
        });
        jPanel1.add(txtQuatity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("تعداد");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("رئٽ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 140, 40));

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 740, 140));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("آئٽم : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("سائز :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 140, 40));

        lblItem.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        getContentPane().add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 160, 40));

        lblSize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        getContentPane().add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 160, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setText("تعداد :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, 40));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        getContentPane().add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuatityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuatityKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String quan = txtQuatity.getText();
            if (!(quan.equals(""))) {
                OrderFrame.billdetailbean.setQuantity(Integer.parseInt(quan));
                txtQuatity.transferFocus();
            }
        }
    }//GEN-LAST:event_txtQuatityKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String price = txtPrice.getText();
            String quan = txtQuatity.getText();
            if (!(price.equals(""))) {
                OrderFrame.billdetailbean.setPrice(Float.parseFloat(price));
                this.dispose();
            } else {
                OrderFrame.billdetailbean.setPrice(0);
                this.dispose();
            }

//            
//            //OrderFrame.setInvoiceTable();
//            
            BillDAO billDAO = new BillDAOImpl();
            if (billDAO.getBillDetails(OrderFrame.billbean) != null) {
                int r = billDAO.updateBillDetails(OrderFrame.billbean);
                if (r != 0) {
                    //JOptionPane.showMessageDialog(null, "update1!");
                } else {
                    //JOptionPane.showMessageDialog(null, "Failed update1!");
                }
            } else {
                int r = billDAO.addBillDetails(OrderFrame.billbean);
                if (r != 0) {
                    //JOptionPane.showMessageDialog(null, "Added1!");
                } else {
                    //JOptionPane.showMessageDialog(null, "Failed1!");
                }
            }

            BillDetailsDAO billDetailsDAO = new BillDetailsDAOImpl();
            
            OrderFrame.billdetailbean.setProductBean(OrderFrame.probean);
            
            if (billDetailsDAO.checkIfProductExists(OrderFrame.billdetailbean)) {
                //update
                int r1 = billDetailsDAO.updateIfProductExists(OrderFrame.billdetailbean);
                if (r1 == 2) {
                    //OrderFrame.setInvoiceTable();
                    //JOptionPane.showMessageDialog(null, "update2!");
                } else {
                    //JOptionPane.showMessageDialog(null, "Failed update2!");
                }
            } else {
                //add
                int r1 = billDetailsDAO.addBillDetails(OrderFrame.billdetailbean);
                if (r1 == 2) {
                    //OrderFrame.setInvoiceTable();
                    //JOptionPane.showMessageDialog(null, "Added2!");
                } else {
                    //JOptionPane.showMessageDialog(null, "Failed2!");
                }
            }

//            
//            System.out.println(OrderFrame.billBean.getBillNumber()+"\t"+OrderFrame.billBean.getAccountBean().getAccountId()
//                    +"\t"+OrderFrame.billBean.getName()+"\t"+OrderFrame.billBean.getTotal()+"\t"+
//                    OrderFrame.billBean.getPaid()+"\t"+OrderFrame.billBean.getDate());
//            System.out.println(OrderFrame.billDetailsBean.getProductBean().getProductId()+"\t"
//                    +OrderFrame.billDetailsBean.getQuantity()+"\t"+OrderFrame.billDetailsBean.getPrice()+"\t"
//                    +OrderFrame.billDetailsBean.getBillBean().getBillNumber());
        }
    }//GEN-LAST:event_txtPriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuantityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuantityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuantityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuantityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuantityDialog dialog = new QuantityDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSize;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuatity;
    // End of variables declaration//GEN-END:variables
}
